=== susanpeng/techwriter/bak/Oxygenproject2/DTDs/letter.dtd
<!-- Parameter Entities - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ENTITY % lists "ol | ul">
<!ENTITY % marking.text "(#PCDATA| mcomment )*">
<!ENTITY % phrases "(#PCDATA| b |i | weblink | mcomment)*">

<!-- Top Level Structure - - - - - - - - - - - - - - - - - - - - - - - -  -->

<!ELEMENT LETTER (HEADING, SALUTATN?, SUBJECT?, body, foot)>
<!ATTLIST LETTER
	id ID #IMPLIED
>

<!-- Salutation - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT SALUTATN (#PCDATA | mcomment)*>
<!-- Body - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT body (p | %lists; )*>
<!-- Heading  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT HEADING (SENDER, DATE, RECIPNT)>
<!ELEMENT SENDER (ADDRESS, PHONE*, FAX?, EMAIL?)>
<!ELEMENT DATE (#PCDATA | mcomment)*>
<!ELEMENT SUBJECT (#PCDATA | b |i | mcomment)*>
<!-- Recipient - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!ELEMENT RECIPNT (NAME, POSITION?, COMPANY?, ADDRESS)>
<!ELEMENT NAME %marking.text;>
<!ELEMENT POSITION %marking.text;>
<!ELEMENT COMPANY %marking.text;>
<!-- Address - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!ELEMENT ADDRESS (ADDRLINE+, CITY, STATE, CODE, COUNTRY? )>
<!ELEMENT ADDRLINE %marking.text;>
<!ELEMENT CITY %marking.text;>
<!ELEMENT STATE %marking.text;>
<!ELEMENT COUNTRY %marking.text;>
<!ELEMENT CODE %marking.text;>
<!-- Phone/Fax/Email - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!ELEMENT PHONE %marking.text;>
<!ELEMENT FAX %marking.text;>
<!ELEMENT EMAIL %marking.text;>
<!-- Foot - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT foot (CLOSURE, NAME, POSITION?, COMPANY?)>
<!ELEMENT CLOSURE %marking.text;>
<!-- Paragraphs - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT p %phrases;>

<!-- External Hypertext Links - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT weblink (#PCDATA)>
<!ATTLIST weblink
	href CDATA #REQUIRED
>

<!-- Numbered List - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!ELEMENT ol (li+)>
<!ELEMENT li (#PCDATA | b | i  | weblink | p | ol | ul | mcomment)*>
<!ATTLIST li id ID #IMPLIED>

<!-- Unnumbered List - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!ELEMENT ul (li+)>
<!ATTLIST ul
	bullet (circle | square | disc) #IMPLIED
	>
<!-- Emphasized Phrases - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT b (#PCDATA)>
<!-- ITALICIZED Phrases - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!ELEMENT i (#PCDATA)>
<!-- Marker's Comments - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!ELEMENT mcomment (commentp+)>
<!ELEMENT commentp (#PCDATA)>

<!-- END - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->

=== susanpeng/techwriter/bak/Oxygenproject2/Source/LetterSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LETTER SYSTEM "../DTDs/letter.dtd">
<?xml-stylesheet type="text/xsl" href="../xslt/student_letter.xsl"?>
<?xml-stylesheet type="text/css" href="../css/letter-oxygen.css"?>
<?altova_sps ..\DTDs\letter.sps?>
<LETTER>
	<HEADING>
		<SENDER>
			<ADDRESS>
				<ADDRLINE>36 5th Avenue</ADDRLINE>
				<CITY>Roxboro</CITY>
				<STATE>Que.</STATE>
				<CODE>Y6T 2T3</CODE>
				<COUNTRY>Canada</COUNTRY>
			</ADDRESS>
			<PHONE>555-5656</PHONE><FAX>555-4444</FAX><EMAIL>bmith@ftrcdcomm.com</EMAIL></SENDER>
		<DATE>April 1, 2009</DATE>
		<RECIPNT><NAME>Joe Smith</NAME><POSITION>Communications Specialist</POSITION><COMPANY>AVNS
				Commmunications</COMPANY>
			<ADDRESS>
				<ADDRLINE>4565 Laird</ADDRLINE>
				<CITY>Gardensview</CITY>
				<STATE>CA</STATE>
				<CODE>23465</CODE>
				<COUNTRY>US</COUNTRY>
			</ADDRESS>
		</RECIPNT>
	</HEADING>
	<SALUTATN>Dear Joe</SALUTATN>
	<SUBJECT>New Business Writing class</SUBJECT>
	<body>
		<p>This is a sample letter. It doesn't make much sense, but it shows you the elements
			available in the letter DTD. This paragraph resides inside a &lt;p> tag. The p tag
			represents a paragraph. </p>
		<p>This is another paragraph. The body of your letter can include the following
			elements:</p>
		<ul bullet="square">
			<li>&lt;p> - Paragraph</li>
			<li>&lt;ul> - Bullet list</li>
			<li>&lt;ol> - Numbered list</li>
		</ul><p>Below is a numbered list:</p><ol>
			<li>Each item in your list is inside an &lt;li> tag.</li>
			<li>To insert a new item in your list, add another &lt;li> tag.</li>
		</ol>
	</body>
	<foot>
		<CLOSURE>Your truly</CLOSURE>
		<NAME>Brent Smith</NAME>
		<POSITION>E-Learning Specialist</POSITION>
		<COMPANY>Online-learning.com</COMPANY>
	</foot>
</LETTER>

=== susanpeng/techwriter/bak/Oxygenproject2/Source/LetterTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LETTER SYSTEM "../DTDs/letter.dtd">
<?xml-stylesheet type="text/xsl" href="../xslt/student_letter.xsl"?>
<?xml-stylesheet type="text/css" href="../css/letter-oxygen.css"?>
<?altova_sps ..\DTDs\letter.sps?>
<LETTER>
    <HEADING>
        <SENDER>
            <ADDRESS>
                <ADDRLINE></ADDRLINE>
                <CITY></CITY>
                <STATE></STATE>
                <CODE></CODE>
            </ADDRESS>
        </SENDER>
        <DATE/>
        <RECIPNT><NAME></NAME>
            <ADDRESS>
                <ADDRLINE></ADDRLINE>
                <CITY></CITY>
                <STATE></STATE>
                <CODE></CODE>
            </ADDRESS>
        </RECIPNT>
    </HEADING>
    <body></body>
    <foot>
        <CLOSURE></CLOSURE>
        <NAME></NAME>
    </foot>
</LETTER>

=== susanpeng/techwriter/bak/Oxygenproject2/Source/LetterAssignment1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LETTER SYSTEM "../DTDs/letter.dtd">
<?xml-stylesheet type="text/xsl" href="../xslt/student_letter.xsl"?>
<?xml-stylesheet type="text/css" href="../css/letter-oxygen.css"?>
<?altova_sps ..\DTDs\letter.sps?>
<LETTER>
    <HEADING>
        <SENDER>
            <ADDRESS>
                <ADDRLINE>9101 Horne Street</ADDRLINE>
                <CITY>Burnaby</CITY>
                <STATE>BC</STATE>
                <CODE>V3N 4M3</CODE>
            </ADDRESS>
            <PHONE>604-555-5555</PHONE>
            <EMAIL>pengyl@gmail.com</EMAIL>
        </SENDER>
        <DATE>October. 26, 2013</DATE>
        <RECIPNT><NAME>Students of PTW</NAME>
            <ADDRESS>
                <ADDRLINE>Suite 112 2-2026 Lanthier Drive</ADDRLINE>
                <CITY>Orleans</CITY>
                <STATE>ON</STATE>
                <CODE>K4A 0N6</CODE>
            </ADDRESS>
        </RECIPNT>
    </HEADING>
    <SALUTATN>Dear classmates</SALUTATN>
    <SUBJECT>Manual Writing Assignments</SUBJECT>
    <body>
        <p>Please consider me as your group partner for the manual writing assignments (assignments #3 and #4). You will certainly benefit from my contribution to the project because I have a strong software development background and excellent teamwork skills.</p>
        <p>I have a master's degree in Electrical Engineering. The strict training required for my degree has made me into a person with a logical way of thinking, strong analytical ability, and problem solving skills.</p>
        <p>I have over 10 years of experience working in the IT field. In the past years, I have
            developed many applications; therefore I can quickly understand how software works. This
            understanding is very important for writing manuals. In the course of my work, I have
            both read and written many instructions, user guides and manuals, so I am able to tell
            what kind of manual or instructions are easily understood.</p>
        <p>I have hands-on working experience with XML, website administration and development, graphics design (Adobe Flash, Photoshop), etc. All of those experiences will help to make the work on manual assignments easy for our group.</p>
        <p>I strongly believe that behind any successful project there is a great team, so I always
            pay close attention to collaborating with co-workers. I am happy to help people and to
            share my opinions, and am also open to new technology and suggestions from others. </p>
        <p>The above points should convince you that working with me will be a pleasant and creative experience. Let's work as a team to fulfill our assignments with a high standard.</p>
        <p>Please contact me by email: pengyl@gmail.com to discuss the formation of an enthusiastic
            team. I look forward to working with you to produce a very excellent and successful
            project.</p>
    </body>
    <foot>
        <CLOSURE>Yours sincerely</CLOSURE>
        <NAME>Yulin Peng</NAME>
    </foot>
</LETTER>
